import numpy as np

from ._delete.utils import expand_tensor
from .expressions import polygon_potential


def _positions(x, y, z):
    """Help function to construct the positions array for the potential"""
    new_array = np.broadcast_arrays(x, y, z)
    shape = new_array[0].shape
    new_array = list(map(np.ravel, new_array))
    new_array = np.stack(new_array, axis=1).astype(float)
    return shape, new_array


def electrode_potential(
    electrode_polygon: list | np.ndarray,
    voltage: float,
    x: np.ndarray,
    y: np.ndarray,
    z: np.ndarray,
    derivative: int,
    cover_height: float,
    pseudo=False,
    cover_nmax=0,
) -> np.ndarray:
    """Computes electrical or pseudo potential generated by an electrode loaded with a given voltage.
    For the pseudopotential a scale factor, which depends on the mass and charge of the ions, and the drive frequency and amplitude is not included.

    Args:
        electrode_polygon (list[np.ndarray] or np.ndarray): Array of shape (n, 2) containing the vertices of the polygonal electrode. Otherwise a list of such arrays for multiple electrodes.
        voltage (float): Voltage applied to the electrode.
        x (np.ndarray): Array of x-coordinates where the potential is evaluated.
        y (np.ndarray): Array of y-coordinates where the potential is evaluated.
        z (np.ndarray): Array of z-coordinates where the potential is evaluated.
        derivative (int): Order of the derivative to compute. i.e. 0 for potential, 1 for field/gradient, 2 for curvature/hessian, etc.
        cover_height (float): Height of the cover.
        pseudo (bool, optional): Whether to compute the pseudo potential. Defaults to False, in which case the electrical potential is computed.
        cover_nmax (int, optional): #TODO. Defaults to 0.

    Raises:
        ValueError: If `derivative` is negative or if `pseudo` is True and `derivative` is greater than 4.

    Returns:
        np.ndarray: Potential evaluated at the specified coordinates, with shape.
    """

    if isinstance(electrode_polygon, np.ndarray):
        electrode_polygon = [electrode_polygon]
    shape, positions_array = _positions(x, y, z)

    if pseudo:
        potential = _compute_pseudo_potential(
            electrode_polygon, voltage, positions_array, derivative, cover_height, cover_nmax
        )
    else:
        potential = _compute_electical_potential(
            electrode_polygon, voltage, positions_array, derivative, cover_height, cover_nmax
        )

    return potential.reshape(shape + (1 * derivative * (3,)))


def _compute_electical_potential(
    electrode_polygon, voltage, positions_array, derivative, cover_height, cover_nmax=0
):

    if derivative >= 2:
        return expand_tensor(
            polygon_potential(
                positions_array,
                electrode_polygon,
                voltage,
                derivative,
                cover_nmax,
                cover_height,
                None,
            )
        )
    else:
        return polygon_potential(
            positions_array,
            electrode_polygon,
            voltage,
            derivative,
            cover_nmax,
            cover_height,
            None,
        )


def _compute_pseudo_potential(
    electrode_polygon, voltage, positions_array, derivative, cover_height, cover_nmax=0
):

    electrical_potentials = [
        expand_tensor(
            polygon_potential(
                positions_array,
                electrode_polygon,
                voltage,
                i,
                cover_nmax,
                cover_height,
                None,
            )
        )
        for i in range(1, derivative + 2)
    ]

    if derivative == 0:
        potential = np.einsum("ij,ij->i", electrical_potentials[0], electrical_potentials[0])
    elif derivative == 1:
        potential = 2 * np.einsum("ij,ijk->ik", electrical_potentials[0], electrical_potentials[1])
    elif derivative == 2:
        potential = 2 * (
            np.einsum(
                "ijk,ijl->ikl",
                electrical_potentials[1],
                electrical_potentials[1],
            )
            + np.einsum(
                "ij,ijkl->ikl",
                electrical_potentials[0],
                electrical_potentials[2],
            )
        )
    elif derivative == 3:
        a = np.einsum("ij,ijklm->iklm", electrical_potentials[0], electrical_potentials[3])
        b = np.einsum("ijk,ijlm->iklm", electrical_potentials[1], electrical_potentials[2])
        a += b
        a += b.transpose(0, 2, 1, 3)
        a += b.transpose(0, 3, 2, 1)
        potential = 2 * a
    elif derivative == 4:
        a = np.einsum("ij,ijklmn->iklmn", electrical_potentials[0], electrical_potentials[4])
        b = np.einsum("ijk,ijlmn->iklmn", electrical_potentials[1], electrical_potentials[3])
        a += b
        a += b.transpose(0, 4, 2, 3, 1)
        a += b.transpose(0, 3, 2, 1, 4)
        a += b.transpose(0, 2, 1, 3, 4)
        c = np.einsum("ijkl,ijmn->iklmn", electrical_potentials[2], electrical_potentials[2])
        a += c
        a += c.transpose(0, 1, 4, 3, 2)
        a += c.transpose(0, 1, 3, 2, 4)
        potential = 2 * a
    else:
        raise ValueError("only know how to generate pseudopotentials up to 4th order")

    return potential


def __cover_potental(voltage, x, y, z, cover_height, derivative=0):

    # TODO! Need to finish impolementing this function.
    shape, positions_array = _positions(x, y, z)
    out = np.zeros((positions_array.shape[0], 2 * derivative + 1), np.double)

    if derivative == 0:
        out[:, 0] += voltage * positions_array[:, 2] / cover_height
    elif derivative == 1:
        out[:, 2] += voltage / cover_height
    else:
        pass
    return None
